import { Geist, Geist_Mono } from "next/font/google";

import type { Metadata } from "next";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="bg-background text-gray-100">
        <nav className="border-line-100 w-full border-b border-b-gray-300">
          <header className="max-w-wrapper mx-auto flex h-[60px] w-full items-center px-4">
            <h1 className="text-lg font-bold text-gray-900">WithPet</h1>
          </header>
        </nav>

        <main className="mx-auto w-full max-w-layout pb-20">{children}</main>
      </body>
    </html>
  );
}
