import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import MSWProvider from "@/providers/MSWProvider";
import ReduxProvider from "@/store/ReduxProvider";

import type { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="bg-background text-gray-100">
        <ReduxProvider>
          <MSWProvider>
            <header className="border-line-light w-full border-b">
              <nav className="container-header mx-auto flex h-[60px] w-full items-center px-4">
                <h1 className="text-lg font-bold text-gray-900">WithPet</h1>
              </nav>
            </header>
            <main className="max-w-layout mx-auto w-full py-20">{children}</main>
          </MSWProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
