#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "커밋 메시지 규칙 검사 중입니다..."

npx --no -- commitlint --edit "$1"

if [ $? -ne 0 ]; then
  echo "커밋 메시지가 규칙에 맞지 않습니다."
  echo "형식 예시: Feat: Header 컴포넌트 생성"
  echo "가능한 타입: Feat | Fix | Chore | Style | Docs | Refactor"
  exit 1
fi

echo "커밋 메시지 규칙 통과."
